# 此清单描述了一个具有堆叠etcd（==与控制平面相同的节点）的高可用拓扑
# 和3个工作节点
# 参见 https://docs.ansible.com/ansible/latest/inventory_guide/intro_inventory.html
# 获取构建清单的技巧

# 配置'ip'变量以将kubernetes服务绑定到与默认接口不同的ip上
# 我们应该为etcd集群设置etcd_member_name。非etcd成员的节点不需要设置该值，
# 或者可以设置为空字符串。

#ansible_connection=local 表示使用本地连接，不需要ssh连接
[all]
node1 ansible_host=test-linux.yunjunyun ansible_connection=local   ip=192.168.52.145 etcd_member_name=etcd1

[kube_control_plane]
node1

[etcd:children]
kube_control_plane

[kube_node]
node1

