## 外部华为云控制器的值
# external_huaweicloud_lbaas_subnet_id: "用于创建LBaaS VIP的Neutron子网ID"
# external_huaweicloud_lbaas_network_id: "用于创建LBaaS VIP的Neutron网络ID"

## 用于认证Keystone API的凭据
## 所有这些凭据都是必需的。默认情况下，这些值将从环境中读取。
# external_huaweicloud_auth_url: "{{ lookup('env','OS_AUTH_URL')  }}"
# external_huaweicloud_access_key: "{{ lookup('env','OS_ACCESS_KEY')  }}"
# external_huaweicloud_secret_key: "{{ lookup('env','OS_SECRET_KEY')  }}"
# external_huaweicloud_region: "{{ lookup('env','OS_REGION_NAME')  }}"
# external_huaweicloud_project_id: "{{ lookup('env','OS_TENANT_ID')| default(lookup('env','OS_PROJECT_ID'),true) }}"
# external_huaweicloud_cloud: "{{ lookup('env','OS_CLOUD') }}"

## 外部华为云控制器镜像的仓库和标签
# external_huawei_cloud_controller_image_repo: "swr.ap-southeast-1.myhuaweicloud.com"
# external_huawei_cloud_controller_image_tag: "v0.26.8"
