## 使用OpenStack时，如果自动检测失败，可以显式指定Cinder版本（已在1.9修复：https://github.com/kubernetes/kubernetes/issues/50461）
# openstack_blockstorage_version: "v1/v2/auto (默认)"
# openstack_blockstorage_ignore_volume_az: yes
## 使用OpenStack时，如果LBaaSv2可用，可以通过以下两个变量启用它。
# openstack_lbaas_enabled: True
# openstack_lbaas_subnet_id: "用于创建LBaaS VIP的Neutron子网ID（非网络ID）"
## 要启用自动浮动IP配置，请指定一个子网。
# openstack_lbaas_floating_network_id: "用于获取浮动IP的Neutron网络ID（非子网ID），默认禁用"
## 覆盖默认LBaaS行为
# openstack_lbaas_use_octavia: False
# openstack_lbaas_method: "ROUND_ROBIN"
# openstack_lbaas_provider: "haproxy"
# openstack_lbaas_create_monitor: "yes"
# openstack_lbaas_monitor_delay: "1m"
# openstack_lbaas_monitor_timeout: "30s"
# openstack_lbaas_monitor_max_retries: "3"

## 外部OpenStack云控制器的值
# external_openstack_lbaas_enabled: true
# external_openstack_lbaas_floating_network_id: "用于获取浮动IP的Neutron网络ID"
# external_openstack_lbaas_floating_subnet_id: "用于获取浮动IP的Neutron子网ID"
# external_openstack_lbaas_method: ROUND_ROBIN
# external_openstack_lbaas_provider: amphora
# external_openstack_lbaas_subnet_id: "用于创建LBaaS VIP的Neutron子网ID"
# external_openstack_lbaas_network_id: "用于创建LBaaS VIP的Neutron网络ID"
# external_openstack_lbaas_manage_security_groups: false
# external_openstack_lbaas_create_monitor: false
# external_openstack_lbaas_monitor_delay: 5s
# external_openstack_lbaas_monitor_max_retries: 1
# external_openstack_lbaas_monitor_timeout: 3s
# external_openstack_lbaas_internal_lb: false
# external_openstack_network_ipv6_disabled: false
# external_openstack_network_internal_networks: []
# external_openstack_network_public_networks: []
# external_openstack_metadata_search_order: "configDrive,metadataService"

## 用于认证Keystone API的应用程序凭据
## 这些设置将优先于可能在环境中设置的用户名和密码
## 所有这些凭据都是必需的
# external_openstack_application_credential_name:
# external_openstack_application_credential_id:
# external_openstack_application_credential_secret:

## Cinder CSI镜像的标签
## registry.k8s.io/sig-storage/csi-attacher
# cinder_csi_attacher_image_tag: "v4.4.2"
## registry.k8s.io/sig-storage/csi-provisioner
# cinder_csi_provisioner_image_tag: "v3.6.2"
## registry.k8s.io/sig-storage/csi-snapshotter
# cinder_csi_snapshotter_image_tag: "v6.3.2"
## registry.k8s.io/sig-storage/csi-resizer
# cinder_csi_resizer_image_tag: "v1.9.2"
## registry.k8s.io/sig-storage/livenessprobe
# cinder_csi_livenessprobe_image_tag: "v2.11.0"

## 要使用Cinder CSI插件配置卷，请将此值设置为true
## 确保已获取OpenStack凭据
# cinder_csi_enabled: true
# cinder_csi_controller_replicas: 1
# storage_classes:
#   - name: "cinder-csi"
#     provisioner: "kubernetes.io/cinder"
#     mount_options:
#       - "discard"
#     parameters:
#       type: "thin"
#       availability: "nova"
#     reclaim_policy: "Delete"
#     volume_binding_mode: "WaitForFirstConsumer"
