---
# geneve 或 vlan
kube_ovn_network_type: geneve

# geneve、vxlan 或 stt。注意：使用 vxlan 和 stt 时某些网络策略可能无法生效，且 stt 需要自定义编译 ovs 内核模块
kube_ovn_tunnel_type: geneve

## 支持容器网络的网卡可以是网卡名称或以逗号分隔的正则表达式组，例如：'enp6s0f0,eth.*'，如果为空则使用默认路由的网卡。
# kube_ovn_iface: eth1
## 覆盖网络中 pod 网卡使用的 MTU（默认网卡 MTU - 100）
# kube_ovn_mtu: 1333

## 启用硬件卸载，禁用流量镜像并将网卡设置为物理端口。确保物理端口绑定了一个 IP 地址。
kube_ovn_hw_offload: false
# 流量镜像
kube_ovn_traffic_mirror: false

# kube_ovn_pool_cidr_ipv6: fd85:ee78:d8a6:8607::1:0000/112
# kube_ovn_default_interface_name: eth0

kube_ovn_external_address: 8.8.8.8
kube_ovn_external_address_ipv6: 2400:3200::1
kube_ovn_external_dns: alauda.cn

# kube_ovn_default_gateway: 10.233.64.1,fd85:ee78:d8a6:8607::1:0
kube_ovn_default_gateway_check: true
kube_ovn_default_logical_gateway: false
# kube_ovn_default_exclude_ips: 10.16.0.1
kube_ovn_node_switch_cidr: 100.64.0.0/16
kube_ovn_node_switch_cidr_ipv6: fd00:100:64::/64

## vlan 配置，设置默认网卡名称和 vlan ID
# kube_ovn_default_interface_name: eth0
kube_ovn_default_vlan_id: 100
kube_ovn_vlan_name: product

## pod 网卡类型，支持：veth-pair 或 internal-port
kube_ovn_pod_nic_type: veth_pair

## 启用负载均衡器
kube_ovn_enable_lb: true

## 启用网络策略支持
kube_ovn_enable_np: true

## 启用外部 VPC 支持
kube_ovn_enable_external_vpc: true

## 启用校验和
kube_ovn_encap_checksum: true

## 启用 SSL
kube_ovn_enable_ssl: false

## dpdk
kube_ovn_dpdk_enabled: false

## 启用与现有 IC 数据库服务器的互连
kube_ovn_ic_enable: false
kube_ovn_ic_autoroute: true
kube_ovn_ic_dbhost: "127.0.0.1"
kube_ovn_ic_zone: "kubernetes"
