# 参见 roles/network_plugin/flannel/defaults/main.yml

## 用于 flannel 操作的接口
## 这实际上是集群级别的清单项
# flannel_interface:

## 通过名称或 IP 的正则表达式选择用于 flannel 操作的接口
## 这实际上是集群级别的清单项
## 示例：选择 IP 在 10.0.0.0/23 网段的接口
## 使用单引号并转义反斜杠
# flannel_interface_regexp: '10\\.0\\.[0-2]\\.\\d{1,3}'

# 您可以选择使用哪种类型的 flannel 后端：'vxlan'、'host-gw' 或 'wireguard'
# 请参阅 flannel 的文档：https://github.com/coreos/flannel/blob/master/README.md
# flannel_backend_type: "vxlan"
# flannel_vxlan_vni: 1
# flannel_vxlan_port: 8472
# flannel_vxlan_direct_routing: false
